### ISSUE TITLE
Hi there ;) poc_receipts_v2

### ISSUE THREAD

**Issue by sajkonariusz** [justinevedovato/Helium-Flick#10]
Could you please update Flick to show new activity receipts? poc_receipts_v2

**Comment by justinevedovato** [comment]
Yeah sure, I've been working on an update, and it's gonna include the missing poc_receipts_v2, which is Beacon in case you were wondering :) I'll be releasing tonight or tomorrow, I still have a few things to fix here and there!

**Comment by justinevedovato** [comment]
Yes, you're right, I forgot about the witnesses but they are treated the same way as v1 anyway, so that's already been fixed for the upcoming update!

**Comment by sajkonariusz** [comment]
Thank You ;)

**Comment by justinevedovato** [comment]
poc_receipts_v2 have been added to the app!
