### ISSUE TITLE
Add support for the SenseCAP API

### ISSUE THREAD

**Issue by radicale** [justinevedovato/Helium-Flick#2]
Here's the documentation https://status-api-doc.sensecapmx.cloud/

I can help with API access if needed.

**Comment by justinevedovato** [comment]
Thank you very much, I'm very interested in adding the manufacturer status support for SenseCAP devices too!

**Comment by sajkonariusz** [comment]
Love the app !!! Will donate as soon as I earn some decent amount of HNT  ;) Can't wait for SenseCAP API support . 
Thank You and keep up the good work.

**Comment by michaelowens** [comment]
The SenseCAP API does not really allow for easy integration into an app like HeliumFlick. They rely on private data (serial numbers) to fetch the hotspot information which you would need to add to every hotspot by hand. This would not be a great user experience.

Unless SC API offers a list of all devices under an API key _or_ allows you to fetch devices by public data (e.g. hotspot address) this is not really feasible.

**Comment by michaelowens** [comment]
I can't find any way of formally requesting a feature on their API, but I put a message in their Discord server this morning requesting either of those features. I'll have to see if they come back to me.
