### ISSUE TITLE
Feature Request: Add desktop notification

### ISSUE THREAD

**Issue by Woutch** [justinevedovato/Helium-Flick#4]
Is it possible to get a desktop popup when new transactions happen? 

Maybe make is configurable which transaction you get to see? Beacons, Mining rewards, Witnesses, ...

Thanks!

**Comment by justinevedovato** [comment]
I did think about that, but at the same time, I also don't want to run useless API calls constantly.
When minimizing the app, you are just hiding it but the page is still active. Each call runs only for the active page, so if you have 36 hotspots, but you were on the page of only one of them, only this one will get its activity feed refreshed every 10 minutes, not all of them. If you are on the main page with the list of hotspots when minimizing, only the calls regarding the balance and daily rewards is renewed every 10 minutes, and not entire activity feeds.
But I take your question in consideration and I still want to have some kind of notification, but I can't apply it to the app as it is currently. I'll have to think of a better way to do it, but that's definitely something that crossed my mind!
Thank you for your suggestion!

**Comment by Woutch** [comment]
Ok, I think you are right, for someone with plenty off hotspots this will generate too many API call's.

If they belong to the same account, you can use the account API maybe?

Just a suggestion, thanks for the great work :-)

**Comment by justinevedovato** [comment]
It should be possible to get notifications whenever the account balance changes, so when a hotspot gets rewards, which is probably what I am gonna look into next! But with the account only, we can't really have infos on the activities of the hotspots, like witness, beacons, etc... But that's something I'll look into, maybe there is a solution that doesn't require that much API calls!
And thank you :)
