### ISSUE TITLE
GPU utilization while open

### ISSUE THREAD

**Issue by ElGranPepo** [justinevedovato/Helium-Flick#6]
i love the app and like to leave it open on the bottom right of y screen, but i noticed when i do (and the app is doing nothing) my task manager will show GPU utilization of two processes.  

any reason for this?
![2022-01-02 16_29_31-Task Manager](https://user-images.githubusercontent.com/60438864/147889957-cb7f742f-58fc-4c97-beec-3e3bd3967d38.png)
?

**Comment by justinevedovato** [comment]
Hello, and hank you for using the app! What you see as two processes are just the app process group and the detail once you open the dropdown, so you are basically looking at the same thing, not two :) As for the GPU usage, my app is using approximately the same as you (1,3%). I'm not an expert and it is my first Electron app, so it could be optimized better in the future, but even though bigger apps use less, 1% still isn't too bad, and definitely not something to worry about :)
